name: LeetCode to GitHub Sync

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:       # Allow manual runs

jobs:
  sync-submissions:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Fetch and save LeetCode submissions (multi-language)
      run: python fetch_leetcode.py
      env:
        LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
        LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
        LEETCODE_CSRF: ${{ secrets.LEETCODE_CSRF }}

    - name: Commit and push updates
      run: |
        git config user.name "leetcode-bot"
        git config user.email "actions@github.com"
        git add leetcode/ last_fetch.json
        git diff --cached --quiet || git commit -m "🤖 Sync LeetCode submissions"
        git push
